# Generated by Django 4.1.3 on 2022-11-30 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "BudgetMonth",
                    models.CharField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        max_length=10,
                    ),
                ),
                ("BudgetAmount", models.FloatField()),
            ],
            options={"db_table": "Budget",},
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category", models.CharField(max_length=50)),
            ],
            options={"db_table": "ExpenseCategory",},
        ),
        migrations.CreateModel(
            name="ExpenseMemberList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ListTitle", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=12)),
                ("IsActive", models.BooleanField(default=False)),
            ],
            options={"db_table": "master",},
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ProfileImage",
                    models.FileField(default="user.png", upload_to="user_profiles/"),
                ),
                ("UserName", models.CharField(max_length=20, unique=True)),
                (
                    "FullName",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "Gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "male"), ("f", "female")],
                        default="",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "BirthDate",
                    models.DateField(blank=True, default="2022-11-01", null=True),
                ),
                (
                    "Address",
                    models.TextField(blank=True, default="", max_length=150, null=True),
                ),
                (
                    "Master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgetApp.master",
                    ),
                ),
            ],
            options={"db_table": "UserProfile",},
        ),
        migrations.CreateModel(
            name="ShareExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ExpenseDate", models.DateTimeField(auto_created=True)),
                (
                    "ExpenseImage",
                    models.FileField(default="user.png", upload_to="expense_images/"),
                ),
                ("Amount", models.FloatField()),
                (
                    "ExpenseCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgetApp.expensecategory",
                    ),
                ),
                (
                    "ExpenseMemberList",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgetApp.expensememberlist",
                    ),
                ),
            ],
            options={"db_table": "ShareExpense",},
        ),
        migrations.AddField(
            model_name="expensememberlist",
            name="Master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="budgetApp.master"
            ),
        ),
        migrations.AddField(
            model_name="expensememberlist",
            name="UserProfile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="budgetApp.userprofile"
            ),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ExpenseDate", models.DateTimeField(auto_created=True)),
                (
                    "ExpenseImage",
                    models.FileField(default="user.png", upload_to="expense_images/"),
                ),
                ("Amount", models.FloatField()),
                ("Description", models.TextField(max_length=255)),
                (
                    "Budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgetApp.budget",
                    ),
                ),
                (
                    "ExpenseCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgetApp.expensecategory",
                    ),
                ),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgetApp.userprofile",
                    ),
                ),
            ],
            options={"db_table": "Expense",},
        ),
        migrations.AddField(
            model_name="budget",
            name="UserProfile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="budgetApp.userprofile"
            ),
        ),
    ]
